### ISSUE TITLE
Commit testing by repository collaborators

### ISSUE THREAD

**Issue by fguerra-hfarm** [fguerra-hfarm/hashtaggers#1]
Once the invite on the repository has been accepted, you are required to do the sequent tasks:

1. Using the `git` package, clone the repository locally with this [GitHub code link](https://github.com/fguerra-hfarm/hashtaggers.git) and then set your work environment on the **test** branch;
2. Change and add to the `README.md` a new line with 'Commit Test: Name Surname' (yours), then perform a commit, and push it to the repository, precisely to the test branch you are working on;
3. If you don't get error messages, check on GitHub for the newest commits, look for yours, and comment on this issue with your commit code.

*Comment on the issue if something does not work to fix things.*

**Comment by fguerra-hfarm** [comment]
@fguerra-hfarm's commit 0bd55418a64eef89f4f19e475a2141207d6bc725

**Comment by VeDiego** [comment]
@VeDiego's commit 7efd8f8e7244cac79e2045476db852fab3308aef

**Comment by LeoLevisse** [comment]
@LeoLevisse's commit 518ad027997e695f644e965ab8b4a63c73fe93e4

**Comment by nicolamrv** [comment]
@nicolamrv's commit f4ce00b60a1a3dcf153bdda871a2349a9762d7a2

**Comment by giorgiovizzini** [comment]
@giorgiovizzini's commit dc8c61c7f5e8f2780cdfdf3ece878f2c5c3bcdb9

**Comment by fguerra-hfarm** [comment]
All members committed and provided the required reference.
