### ISSUE TITLE
Creation of README.md for each package

### ISSUE THREAD

**Issue by nicolamrv** [fguerra-hfarm/hashtaggers#10]
We are at the last stages of the project so now it's time to explain in a captivating way what we've accomplished and how anyone can use our project. We also need to explain in a more technical way all the packages that we've implemented to make the project working.

- [x] **hashtaggers**: main `README.md` where we present everything in all the aspects;

- [x] **hashtagify_package**: specific technical package `README.md`;

- [x] **use_csv_package**: specific technical package `README.md`;

🤖 🥇 ✅ 🤍

**Comment by giorgiovizzini** [comment]
First draft of the Hashtaggers repository made at commit 670a2c25518426af372e309685c1660b11bd0bd8.

**Comment by LeoLevisse** [comment]
First draft of the use_csv_package made with commit a7c8e1fc751e442ef9eac57a5398b55c5db603c5 and with commit 132e3525645f43873840b744a17850a0c30b877c by @nicolamrv the first draft of the hashtagify_package.

**Comment by fguerra-hfarm** [comment]
Final version of the documentation committed and merged with the main in 85dacc1d72d8e9e1e0a28d18598ba78ca979ff0f! We are done!
