### ISSUE TITLE
Creation and organization of new branches

### ISSUE THREAD

**Issue by fguerra-hfarm** [fguerra-hfarm/hashtaggers#2]
The project development process needs different branches based on different functionality necessities. 

***Branches to create*** (names and files may vary):
1. *use_dataset*: File .py to clean and manipulate a given dataset;
2. *api_ritekit*: in order to get in the mindset and knowledge of using python packages such as `request` and `json`, while we wait for the user credentials for our API, let's start playing with a simple one provided by [Ritekit](https://ritekit.com) that does similar things; 
3. *api_hashtagify*: writing of the code needed to implement the API service provided by [Hashtagify](https://hashtagify.me), start the variable selection from the JSON output for our prints, computer packages check for the user (`pip` install control), and usage of the `argparse` package to guide the user.
   - File .py to generate, check and use the needed access token for the API;
   - File .py to use the API and get the hashtag insights from the output;
   - File main.py to recall all the developed functions and ready to be launched through the terminal;
   - File setup.py to check and make sure that the user is ready to launch the main.py file;
   - Files needed to complete the package and comply with the global repository package rules (added over time if/when needed).

They all will be merged to the principal **dev** branch (development branch) once completed and subsequently merged to the **main** (final version of all the files).

**Comment by fguerra-hfarm** [comment]
*use_dataset* branch created. The commit reference for these creations will be from the main branch at 0bd55418a64eef89f4f19e475a2141207d6bc725.

Could you @nicolamrv and @VeDiego create the *api_ritekit* and *api_hashtagify* ones correspondingly?

**Comment by nicolamrv** [comment]
@fguerra-hfarm I've created the *api_ritekit* branch

**Comment by VeDiego** [comment]
@fguerra-hfarm I have created the *api_hashtagify* branch
