### ISSUE TITLE
Package to clean and manipulate a given dataset

### ISSUE THREAD

**Issue by giorgiovizzini** [fguerra-hfarm/hashtaggers#3]
First, we should start by writing some code that **reads**, **cleans**, and brings an **utilizable output** of hashtags to be ready for other functions. We will work from a `.csv` file that will be our sample dataset of Twitter posts.

  Goal: this package should extrapolate hashtags indifferently from which social platform we are dealing with, it should work globally and read + extrapolate only the "#tag" present in the given post.  

Working branch: *use_dataset*

**Comment by giorgiovizzini** [comment]
I have written the first version of the code to prepare the hashtags (commit reference cb07790937f3de1292c0346370824a242be54cf6). It can be improved in several ways, I am looking forward for any enhancement.

**Comment by nicolamrv** [comment]
@giorgiovizzini I've shortened and improved the code by using some new packages such as `string` and `re` to clean up the given dataset in a more effective way. The script can still be improved though (commit reference 01f59293925a06afd2f15462961e1c034f640fbd).

**Comment by fguerra-hfarm** [comment]
@giorgiovizzini @nicolamrv with my last commit (reference 5789b9744c7345a4e2d3e7663e3ec6117795bf35) the code now should be ready and in line with the requests of the issue.
I added also the script `ht_csv.py` which exports, by using a modified version of the code in `posts_csv.py`, an actual new `.csv` file that will have every single hashtag present in the given dataset of social posts (reference d067756117c3fd01800288355f70635dab17822e).
