### ISSUE TITLE
RiteKit API

### ISSUE THREAD

**Issue by LeoLevisse** [fguerra-hfarm/hashtaggers#4]
Let's start playing with a simple service provided by [RiteKit](https://ritekit.com) that does similar things to what we have to do while we wait for our hashtagify credentials as stated in issue #2. 

Working branch: *api_ritekit*

**Comment by LeoLevisse** [comment]
I tried to use the API, as you can see from my first commit 6af7c82c05000cb4fbf6a72378e341d52546a65b.

**Comment by VeDiego** [comment]
I improved the code and it is now working with the module #3 (you can see it at the commit: 204b60b53600d1fffec08f7a1150684c59482a8d). We can now start with hashtagify api as soon as we have the credentials
