### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by VeDiego** [fguerra-hfarm/hashtaggers#5]
Once we come up with the final version of a .py file, if this one is a component of one of the packages, we need to make sure that it is PEP 8 compliant.
To do that we have been recommended to use the `pycodestyle` package.

At the last commit, when the file is compliant with this coding writing guideline, we state its readiness so we know that we can start to merge it to the next branch in the hierarchy and that one is the last commit.

**Comment by LeoLevisse** [comment]
In my last commit 42cfaebc9e3c19307c4ddbacd4e66382d5fa78b0 I developed the testing for `use_csv_package` which passed all the testings and it is PEP-8 compliant. I checked it by using the required tool of `pycodestyle` package.

**Comment by VeDiego** [comment]
In my last commits 4137c2146680e5839ca071b72756d4888857b15f 09ff6262cb1fb66ae220e19caf34340b5373de47 I developed the testing for `hashtagify_package`, which passed all the testings, and I uploaded the final version of the `api_hashtagify.py` module. Both are PEP-8 compliant! I checked by using the required tool of `pycodestyle` package.

**Comment by fguerra-hfarm** [comment]
In my last commit 2511d0ecd6140d2f7f5be006b51a0a7f4a1bdc34 I uploaded the final versions of `main.py` and `setup.py` modules which are PEP-8 compliant. I checked them by using the required tool of `pycodestyle` package.

**Comment by nicolamrv** [comment]
In my last commit 266aef1c6dafe111d2f57624798c4abca6c09efe I uploaded the final version of `posts_csv.py` which is PEP-8 compliant. I checked it by using the required tool of `pycodestyle` package.

**Comment by LeoLevisse** [comment]
In my last commit aa5508d89fadc1fe59a0b6c2cea45fd65f56f3fa  I uploaded the final version of `ht_csv.py` which is PEP-8 compliant. I checked it by using the required tool of `pycodestyle` package.

**Comment by fguerra-hfarm** [comment]
I see that @giorgiovizzini (commit c7dbc2628236a883527968cb9e5fc3c7467d6632), which forgot to comment on the issue 😡, uploaded the final version of `api_token.py`, which is PEP-8 compliant, and for sure it is checked by using the required tool of `pycodestyle` package since we made it together.

We can close the issue since all the files have been updated and are compliant! 💯
