### ISSUE TITLE
Project's folders structure

### ISSUE THREAD

**Issue by giorgiovizzini** [fguerra-hfarm/hashtaggers#7]
### Structure

Finalized the code for the usage of the API, which works with the other python files, we have to start creating a structure of our project files.

That is from what we thought to implement today in the Zoom call

1.  **main**
    - [x] `__init__.py`
    - [x] `main.py` (to run the project)
    - [x] `setup.py`
    - [x] `README.md`
&nbsp;
2. **hashtagify_package** 
    - [x] `__init__.py` 
    - [x] `api_hashtagify.py`
    - [x] `api_token.py`
    - [x] `README.md`
    - [x] *tests* subfolder with `test_api_hashtagify.py` (to test the code)
&nbsp;
3. **use_csv_package**
    - [x] `__init__.py`
    - [x] `posts_csv.py`
    - [x] `ht_csv.py` 
    - [x] `README.md`
    - [x] *data* subfolder where the user can allocate the `.csv` dataset and where the output of `ht_csv.py` will be generated
    - [x] *tests* subfolder with `test_posts_csv.py` (to test the code)

The testing will be implemented by using the [unittest](https://docs.python.org/3/library/unittest.html) module

We got it :fire:

**Comment by giorgiovizzini** [comment]
@fguerra-hfarm could you type the checklist we made regarding this issue? As you can see, I've also tried the first version of the `main.py`, which, of course, still needs a lot of development (commit reference da6a1e10f22462af12427c48c45386258891d0fe).

**Comment by fguerra-hfarm** [comment]
### Structure
That is from what we thought to implement today in the Zoom call

- [ ] **main**
    1. `__init__.py`
    2. `main.py` (to run the project)
    3. `setup.py`
    4. `README.md`

- [ ] **hashtagify_package** 
    1. `__init__.py` 
    2. `api_hashtagify.py`
    3. `api_token.py`
    4. `README.md`
    5. *tests* subfolder with `test_api_hashtagify.py` and `test_api_token.py` (to test the code)

- [ ] **use_csv_package folder**
    1. `__init__.py`
    2. `posts_csv.py`
    3. `ht_csv.py` 
    4. `README.md`
    5. *data* subfolder where the user can allocate the `.csv` dataset and where the output of `ht_csv.py` will be generated
    6. *tests* subfolder with `test_posts_csv.py` and `test_ht_csv.py` (to test the code)

The testing will be implemented by using the [unittest](https://docs.python.org/3/library/unittest.html) module

We got it :fire:

**Comment by fguerra-hfarm** [comment]
Update the checklist everytime we make some progress by finish that element (e.g. finishing the code of `api_hashtagify.py` means **DONE** in the list!)

**Comment by VeDiego** [comment]
Checklist completed. We can close the issue
