### ISSUE TITLE
Package testing

### ISSUE THREAD

**Issue by nicolamrv** [fguerra-hfarm/hashtaggers#8]
We need to implement the testing of the packages: 

- `hashstagify_package` --> testing input values to know valid/invalid entries, and edge/bounday/corner cases of the tested 
    function;

- `use_csv_package` --> testing scenarios regarding the use of a .csv file, which may not exists in the directory and/or it is 
    empty.

As stated in issue #7 we need to use the **unittest** module.

**Comment by LeoLevisse** [comment]
Developed and passed all the testings for the package `use_csv_package` in the commit 42cfaebc9e3c19307c4ddbacd4e66382d5fa78b0.

**Comment by VeDiego** [comment]
Developed and passed all the testings for the package `hashtagify_package` in the commit 4137c2146680e5839ca071b72756d4888857b15f. 
In addition I added the folder needed for your testing in commit 29bba5fb8c62c9ca6b6e89a6ee81d50a7d21a321 with `.gitignore` file so we can store the folder in the git add repository.
