### ISSUE TITLE
Docstrings and Pydoc

### ISSUE THREAD

**Issue by giorgiovizzini** [fguerra-hfarm/hashtaggers#9]
Now it is the phase of implementing comments and docstrings in all our Python modules and packages. In each one of those writings we need to describe the function or the step made in the actual line of code. 

Once we finished we need to check everything by using the [Pydoc library](https://docs.python.org/3/library/pydoc.html). 
As we have seen together during the meetings it will read through the lines and it will print just the docstrings that we implemented. It should run with the command `$ pydoc -w <namefile>` and generate a `.html` file output of the module's docstrings.

**Comment by fguerra-hfarm** [comment]
Everything has been implemented and later checked with also Pydoc for the docstring (generated a specific `.html` export for each module). We can reference issue #5 for completeness regarding the PEP-8 compliance.
